import { defineComponent, ref } from 'vue'
import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import type { AdminGroup } from '@/types'

const mocks = vi.hoisted(() => ({ files: vi.fn(), oauth: vi.fn(), refresh: vi.fn(), exchange: vi.fn(), create: vi.fn(), post: vi.fn(), sync: vi.fn(), generateAuthUrl: vi.fn(), getById: vi.fn(), update: vi.fn() }))
vi.mock('@/api/admin', () => ({ adminAPI: { accounts: { importCPAAuthFiles: mocks.files, importOpenAIOAuthToCPA: mocks.oauth, create: mocks.create, getById: mocks.getById, update: mocks.update } } }))
vi.mock('@/api/client', () => ({ apiClient: { post: mocks.post } }))
vi.mock('@/api/admin/accounts', () => ({ syncCPAAccounts: mocks.sync }))
vi.mock('vue-i18n', async () => ({ ...await vi.importActual('vue-i18n'), useI18n: () => ({ locale: ref('zh'), t: (key: string) => key }) }))
vi.mock('@/composables/useOpenAIOAuth', () => ({ useOpenAIOAuth: () => ({
  authUrl: ref(''), sessionId: ref('session'), oauthState: ref('expected-state'), loading: ref(false), error: ref(''), harnessKind: ref(''), piOwnerUserId: ref<number | undefined>(),
  generateAuthUrl: mocks.generateAuthUrl, resetState: vi.fn(), validateRefreshToken: mocks.refresh, exchangeAuthCode: mocks.exchange,
  buildCredentials: (value: Record<string, unknown>) => ({ ...value })
}) }))
vi.mock('../CPABridgeSetup.vue', () => ({default: {template: '<div />'}}))
import CreateAccountModal from '../CreateAccountModal.vue'
const Dialog = defineComponent({ props: ['show'], template: '<div v-if="show"><slot/><slot name="footer"/></div>' })
const render = (groups?: AdminGroup[], currentUserId?: number, initialBackend?: 'cpa' | 'basispoints') => mount(CreateAccountModal, { props: { show: true, groups, currentUserId, initialBackend }, global: { stubs: { BaseDialog: Dialog, CPABridgeSetup: true } } })
const activeOpenAIGroup = { id: 42, name: 'Pi clients', platform: 'openai', status: 'active', is_exclusive: true } as AdminGroup

describe('account import backend boundaries', () => {
  it('retries importing exchanged credentials without redeeming an OAuth code twice', async () => {
    mocks.exchange.mockResolvedValue({access_token:'synthetic'})
    mocks.oauth.mockRejectedValueOnce(new Error('temporary upstream failure')).mockResolvedValueOnce({auth_name:'retry.json',bridge_account_id:0})
    const wrapper=render(undefined,undefined,'basispoints')
    await wrapper.get('[data-testid="cpa-callback"]').setValue('http://localhost/callback?code=once&state=expected-state')
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click'); await flushPromises()
    expect(mocks.exchange).toHaveBeenCalledTimes(1)
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click'); await flushPromises()
    expect(mocks.exchange).toHaveBeenCalledTimes(1)
    expect(mocks.oauth).toHaveBeenCalledTimes(2)
    expect(wrapper.emitted('created')).toHaveLength(1)
  })
  it('opens the dedicated plugin path in OAuth mode and explains required authorization', async () => {
    const wrapper = render(undefined, undefined, 'basispoints')
    expect(wrapper.get('[data-testid="cpa-tab-oauth"]').attributes('aria-selected')).toBe('true')
    expect((wrapper.get('[data-testid="basispoints-import-enabled"]').element as HTMLInputElement).checked).toBe(true)
    expect(wrapper.get('[data-testid="cpa-generate-auth"]').text()).toContain('CPA / Codex')
    expect(wrapper.get('[data-testid="basispoints-auth-method"]').text()).toContain('不是微软 Excel')
    expect(wrapper.text()).toContain('并非免授权')
    await wrapper.get('[data-testid="cpa-generate-auth"]').trigger('click')
    expect(mocks.generateAuthUrl).toHaveBeenCalledWith(null)
  })
  it('binds only exact synchronized accounts and preserves their existing extras', async () => {
    mocks.exchange.mockResolvedValue({access_token:'synthetic'})
    mocks.oauth.mockResolvedValue({auth_name:'one.json',bridge_account_id:0})
    mocks.sync.mockResolvedValue({created:1,updated:0,identities:1,account_ids:[101]})
    mocks.getById.mockResolvedValue({platform:'openai',extra:{cpa_auth_id:'auth-1',existing_setting:true}})
    mocks.update.mockResolvedValue({})
    const wrapper = render(undefined, undefined, 'basispoints')
    await wrapper.get('[data-testid="cpa-callback"]').setValue('http://localhost/callback?code=test&state=expected-state')
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click'); await flushPromises()
    expect(mocks.sync).toHaveBeenCalledWith(['one.json'])
    expect(mocks.update).toHaveBeenCalledTimes(1)
    expect(mocks.update).toHaveBeenCalledWith(101,{extra:{cpa_auth_id:'auth-1',existing_setting:true,openai_basispoints_enabled:true}})
    expect(wrapper.get('[role="status"]').text()).toContain('用户模型名保持不变')
    expect(wrapper.get('[role="status"]').text()).toContain('配置分组并启用')
  })
  it('does not claim plugin binding success when synchronization returns no account IDs', async () => {
    mocks.exchange.mockResolvedValue({access_token:'synthetic'})
    mocks.oauth.mockResolvedValue({auth_name:'one.json',bridge_account_id:0})
    mocks.sync.mockResolvedValue({created:1,updated:0,identities:1,account_ids:[]})
    const wrapper = render(undefined, undefined, 'basispoints')
    await wrapper.get('[data-testid="cpa-callback"]').setValue('http://localhost/callback?code=test&state=expected-state')
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click'); await flushPromises()
    expect(mocks.update).not.toHaveBeenCalled()
    expect(wrapper.get('[role="alert"]').text()).toContain('未启用插件覆盖')
    expect(wrapper.get('[role="status"]').text()).not.toContain('已启用 Excel')
  })
  it('keeps the native backend when the administrator unticks plugin override', async () => {
    mocks.exchange.mockResolvedValue({access_token:'synthetic'})
    mocks.oauth.mockResolvedValue({auth_name:'one.json',bridge_account_id:0})
    mocks.sync.mockResolvedValue({created:1,updated:0,identities:1,account_ids:[101]})
    const wrapper = render(undefined, undefined, 'basispoints')
    await wrapper.get('[data-testid="basispoints-import-enabled"]').setValue(false)
    await wrapper.get('[data-testid="cpa-callback"]').setValue('http://localhost/callback?code=test&state=expected-state')
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click'); await flushPromises()
    expect(mocks.update).not.toHaveBeenCalled()
    expect(wrapper.find('[role="alert"]').exists()).toBe(false)
  })
  beforeEach(() => { vi.clearAllMocks(); mocks.files.mockResolvedValue({ created: 1, updated: 0, failed: 0, errors: [] }); mocks.oauth.mockResolvedValue({ bridge_account_id: 30 }); mocks.sync.mockResolvedValue({ created: 0, updated: 0, identities: 0 }); mocks.post.mockResolvedValue({}) })
  it('exposes no arbitrary direct backend URL or separate Sub2 account creation', () => {
    const wrapper = render()
    expect(wrapper.get('[data-testid="cpa-only-notice"]').text()).toContain('CPA')
    expect(wrapper.find('[data-testid="openai-runtime-backend-direct"]').exists()).toBe(false)
    expect(wrapper.find('[name="base_url"]').exists()).toBe(false)
    expect(wrapper.text()).not.toContain('Sub2 直连')
  })
  it('imports JSON only through CPA and clears credentials after success', async () => {
    const wrapper = render()
    await wrapper.get('[data-testid="cpa-json"]').setValue('{"access_token":"synthetic"}')
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click'); await flushPromises()
    expect(mocks.files).toHaveBeenCalledWith(['{"access_token":"synthetic"}'], expect.objectContaining({priority: 0,weight: 1,request_retry: 0,proxy_id:null}))
    expect(mocks.create).not.toHaveBeenCalled()
    expect(wrapper.emitted('created')).toHaveLength(1)
    expect((wrapper.get('[data-testid="cpa-json"]').element as HTMLTextAreaElement).value).toBe('')
  })
  it('shows partial import errors without falling back to Sub2', async () => {
    mocks.files.mockResolvedValue({ created: 1, updated: 0, failed: 1, errors: [{ index: 2, message: 'expired' }] })
    const wrapper = render()
    await wrapper.get('[data-testid="cpa-json"]').setValue('[{},{}]')
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click'); await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toContain('#2: expired')
    expect(mocks.create).not.toHaveBeenCalled()
  })
  it.each(['file', 'json'])('imports %s without a business bridge and shows a routing warning', async (mode) => {
    mocks.files.mockResolvedValue({ created: 1, updated: 0, failed: 0, errors: [], items: [{ index: 1, action: 'imported_cpa' }] })
    const wrapper = render()
    const synthetic = '{"tokens":{"access_token":"synthetic"}}'
    if (mode === 'file') {
      const input = wrapper.get('[data-testid="cpa-files"]')
      Object.defineProperty(input.element, 'files', { value: [{ size: synthetic.length, text: () => Promise.resolve(synthetic) }] })
      await input.trigger('change'); await flushPromises()
    } else {
      await wrapper.get('[data-testid="cpa-json"]').setValue(synthetic)
    }
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click'); await flushPromises()
    expect(mocks.files).toHaveBeenCalledWith([synthetic], expect.any(Object))
    expect(wrapper.get('[data-testid="cpa-routing-warning"]').text()).toContain('尚未配置业务桥接')
    expect(wrapper.get('[role="status"]').text()).toContain('1')
    expect(mocks.create).not.toHaveBeenCalled()
  })
  it('does not show a green success message when all imports failed', async () => {
    mocks.files.mockResolvedValue({ created: 0, updated: 0, failed: 1, errors: [{ index: 1, message: '授权未通过验证' }] })
    const wrapper = render()
    await wrapper.get('[data-testid="cpa-json"]').setValue('{}')
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click'); await flushPromises()
    expect(wrapper.find('[role="status"]').exists()).toBe(false)
    expect(wrapper.get('[role="alert"]').text()).toContain('授权未通过验证')
  })
  it('preserves an unrotated refresh token while importing into CPA', async () => {
    mocks.refresh.mockResolvedValue({ access_token: 'fresh', id_token: 'id' })
    const wrapper = render()
    await wrapper.get('[data-testid="cpa-tab-refresh"]').trigger('click')
    await wrapper.get('[data-testid="cpa-refresh-tokens"]').setValue('original-refresh')
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click'); await flushPromises()
    expect(mocks.oauth).toHaveBeenCalledWith(expect.objectContaining({ refresh_token: 'original-refresh', access_token: 'fresh' }), expect.objectContaining({disabled:false,weight:1}))
    expect(mocks.create).not.toHaveBeenCalled()
  })
  it('rejects a mismatched OAuth callback before exchanging credentials', async () => {
    const wrapper = render()
    await wrapper.get('[data-testid="cpa-tab-oauth"]').trigger('click')
    await wrapper.get('[data-testid="cpa-callback"]').setValue('http://localhost/callback?code=test&state=wrong')
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click'); await flushPromises()
    expect(mocks.exchange).not.toHaveBeenCalled()
    expect(wrapper.get('[role="alert"]').text()).toContain('不匹配')
  })
  it('keeps credentials visible for correction on an import failure and never falls back', async () => {
    mocks.files.mockRejectedValue(new Error('CPA unavailable'))
    const wrapper = render()
    await wrapper.get('[data-testid="cpa-json"]').setValue('{}')
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click'); await flushPromises()
    expect(wrapper.emitted('created')).toBeUndefined()
    expect(mocks.create).not.toHaveBeenCalled()
    expect(wrapper.get('[role="alert"]').text()).toContain('CPA unavailable')
  })
  it('requires an explicit active OpenAI group and sends only the chosen group when creating Pi', async () => {
    const inactive = { id: 43, name: 'Inactive OpenAI', platform: 'openai', status: 'inactive' } as AdminGroup
    const anthropic = { id: 44, name: 'Anthropic', platform: 'anthropic', status: 'active' } as AdminGroup
    const wrapper = render([activeOpenAIGroup, inactive, anthropic])
    await wrapper.get('[data-testid="cpa-tab-oauth"]').trigger('click')
    await wrapper.get('[data-testid="openai-harness-kind"]').setValue('pi')
    await wrapper.get('[data-testid="pi-owner-user-id"]').setValue('7')
    const groupSelect = wrapper.get('[data-testid="pi-group-id"]')
    expect(groupSelect.findAll('option').map((option) => option.text())).toEqual(['请选择已启用的 OpenAI 分组', 'Pi clients'])
    await wrapper.get('[data-testid="cpa-generate-auth"]').trigger('click')
    expect(mocks.generateAuthUrl).not.toHaveBeenCalled()
    expect(wrapper.get('[role="alert"]').text()).toContain('OpenAI 分组')

    await groupSelect.setValue('42')
    await wrapper.get('[data-testid="cpa-generate-auth"]').trigger('click')
    expect(mocks.generateAuthUrl).toHaveBeenCalledWith(null)
    await wrapper.get('[data-testid="cpa-callback"]').setValue('http://localhost:1455/auth/callback?code=pi-code&state=expected-state')
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click')
    await flushPromises()
    expect(mocks.post).toHaveBeenCalledWith('/admin/openai/create-pi-account', {
      session_id: 'session', code: 'pi-code', state: 'expected-state', pi_owner_user_id: 7, group_ids: [42]
    })
    expect(mocks.oauth).not.toHaveBeenCalled()
    expect(mocks.sync).not.toHaveBeenCalled()
    expect(wrapper.emitted('created')).toHaveLength(1)
  })
  it('does not create Pi when no active OpenAI group is available', async () => {
    const wrapper = render([])
    await wrapper.get('[data-testid="cpa-tab-oauth"]').trigger('click')
    await wrapper.get('[data-testid="openai-harness-kind"]').setValue('pi')
    await wrapper.get('[data-testid="pi-owner-user-id"]').setValue('7')
    expect(wrapper.get('[data-testid="pi-no-groups"]').text()).toContain('没有可用')
    await wrapper.get('[data-testid="cpa-callback"]').setValue('http://localhost:1455/auth/callback?code=pi-code&state=expected-state')
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click')
    await flushPromises()
    expect(mocks.post).not.toHaveBeenCalled()
    expect(wrapper.get('[role="alert"]').text()).toContain('OpenAI 分组')
  })
  it('imports one Pi auth.json into an owner-bound group without calling CPA', async () => {
    const wrapper = render([activeOpenAIGroup], 7)
    await wrapper.get('[data-testid="pi-auth-backend"]').setValue('pi')
    expect((wrapper.get('[data-testid="pi-auth-owner-user-id"]').element as HTMLInputElement).value).toBe('7')
    await wrapper.get('[data-testid="pi-auth-group-id"]').setValue('42')
    await wrapper.get('[data-testid="cpa-json"]').setValue('{"auth_mode":"chatgpt","tokens":{}}')
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click')
    await flushPromises()
    expect(mocks.post).toHaveBeenCalledWith('/admin/openai/import-pi-auth', {
      content: '{"auth_mode":"chatgpt","tokens":{}}', pi_owner_user_id: 7, group_ids: [42]
    })
    expect(mocks.files).not.toHaveBeenCalled()
    expect(mocks.sync).not.toHaveBeenCalled()
    expect(wrapper.get('[role="status"]').text()).toContain('已启用并参与调度，并发为 10')
    expect(wrapper.emitted('created')).toHaveLength(1)
    expect((wrapper.get('[data-testid="cpa-json"]').element as HTMLTextAreaElement).value).toBe('')
  })
  it('allows an existing public OpenAI group for Pi import', async () => {
    const wrapper = render([{ ...activeOpenAIGroup, is_exclusive: false } as AdminGroup], 7)
    await wrapper.get('[data-testid="pi-auth-backend"]').setValue('pi')
    expect(wrapper.get('[data-testid="pi-auth-group-id"]').findAll('option')).toHaveLength(2)
    await wrapper.get('[data-testid="pi-auth-group-id"]').setValue('42')
    await wrapper.get('[data-testid="cpa-json"]').setValue('{}')
    await wrapper.get('[data-testid="cpa-import-submit"]').trigger('click')
    await flushPromises()
    expect(wrapper.emitted('created')).toHaveLength(1)
    expect(mocks.post).toHaveBeenCalledWith('/admin/openai/import-pi-auth', { content: '{}', pi_owner_user_id: 7, group_ids: [42] })
    expect(wrapper.get('[role="status"]').text()).toContain('并发为 10')
  })
})
